### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by bombcar**
update a bunch of gradle and get it to build

### CODE REVIEW

**Review by Dream-Master — COMMENTED** [review]
I would't drop mod support even if we dont use the mode.
@GTNewHorizons/core @GTNewHorizons/developers what do you think

**Comment by glowredman** [comment]
I agree. As long as it doesn't require a considerable effort to keep the compat to other mods, we should keep them, because it makes it easier to use outside of GTNH.
TL;TR, we shouldn't actively kill compat to non-GTNH mods

**Comment by bombcar** [comment]
> I agree. As long as it doesn't require a considerable effort to keep the compat to other mods, we should keep them, because it makes it easier to use outside of GTNH.
> TL;DR, we shouldn't actively kill compat to non-GTNH mods

ok I can revert that part and see if I can make the build dependency optional.

**Comment by bombcar** [comment]
Ok BR and Mek are back and dependent on cursemaven so they build

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
